name: 自动拉取并精简转换为TXT

on: 
  schedule: 
    # 每天世界标准时间 13:00 自动运行（严格对应北美东部时间早上 09:00）
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  main:
    name: update migu
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: fetch and modify
      run: |
        python filter.py
    - name: CommitAndPush
      run: |
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        git config --global user.email "github@github.com"
        git config --global user.name "Github Actions"
        
        # 严格使用单引号外包裹，内部使用标准表达式
        git clone 'https://'${{ github.actor }}':'${{ secrets.GITHUB_TOKEN }}'@://github.com{{ github.repository }}'.git'
        cd "$REPO_NAME" || exit 1

        [ -f "../cctv_clean.txt" ] && mv ../cctv_clean.txt ./cctv_clean.txt || true

        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update: $(date +'%Y-%m-%d %H:%M:%S') UTC"
          git push origin main
        fi
